[HyperspectralImageProcessor 2024-07-18 12:43:40] WARNING: a thread raised an Exception, which will be logged as an error below but not re-raised. The thread that raised the error will be restarted.
Traceback (most recent call last):
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsitoolbox/utilities/exception_tracking_thread.py", line 29, in run
    super().run(*args, **kwargs)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/controlled_message_reproducer.py", line 90, in _run_worker
    self.__consume_messages_while_alive(consumer)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/controlled_message_reproducer.py", line 173, in __consume_messages_while_alive
    retval = self._process_message(self.lock, msg)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/data_file_io/actor/data_file_stream_reproducer.py", line 281, in _process_message
    new_msg = self._get_processing_result_message_for_file(
  File "/Users/namanparikh/Documents/GitHub/paradim/reu2024-hyperspectral-camera/streaming/final_scripts/hyperspec_processor.py", line 32, in _get_processing_result_message_for_file
    return ReproducerMessage(DataFile(output_filepath))
TypeError: Can't instantiate abstract class ReproducerMessage with abstract method msg_value
[HyperspectralImageProcessor 2024-07-18 12:43:40] WARNING: a thread raised an Exception, which will be logged as an error below but not re-raised. The thread that raised the error will be restarted.
Traceback (most recent call last):
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsitoolbox/utilities/exception_tracking_thread.py", line 29, in run
    super().run(*args, **kwargs)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/controlled_message_reproducer.py", line 90, in _run_worker
    self.__consume_messages_while_alive(consumer)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/controlled_message_reproducer.py", line 173, in __consume_messages_while_alive
    retval = self._process_message(self.lock, msg)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/data_file_io/actor/data_file_stream_reproducer.py", line 281, in _process_message
    new_msg = self._get_processing_result_message_for_file(
  File "/Users/namanparikh/Documents/GitHub/paradim/reu2024-hyperspectral-camera/streaming/final_scripts/hyperspec_processor.py", line 32, in _get_processing_result_message_for_file
    return ReproducerMessage(DataFile(output_filepath))
TypeError: Can't instantiate abstract class ReproducerMessage with abstract method msg_value
[HyperspectralImageProcessor 2024-07-18 12:46:14] WARNING: failed to synchronously commit offset of last message received. Duplicate messages may be read the next time this Consumer is started. Error will be logged below but not re-raised.
Traceback (most recent call last):
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/controlled_message_reproducer.py", line 221, in __commit_last_message_offset
    tps = consumer.commit(self.last_message, asynchronous=False)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/openmsistream_consumer.py", line 314, in commit
    return self._consumer.commit(message=message, asynchronous=asynchronous)
cimpl.KafkaException: KafkaError{code=ILLEGAL_GENERATION,val=22,str="Commit failed: Broker: Specified group generation id is not valid"}
[HyperspectralImageProcessor 2024-07-18 12:46:14] WARNING: failed to synchronously commit offset of last message received. Duplicate messages may be read the next time this Consumer is started. Error will be logged below but not re-raised.
Traceback (most recent call last):
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/controlled_message_reproducer.py", line 221, in __commit_last_message_offset
    tps = consumer.commit(self.last_message, asynchronous=False)
  File "/Users/namanparikh/opt/anaconda3/envs/openmsi/lib/python3.9/site-packages/openmsistream/kafka_wrapper/openmsistream_consumer.py", line 314, in commit
    return self._consumer.commit(message=message, asynchronous=asynchronous)
cimpl.KafkaException: KafkaError{code=ILLEGAL_GENERATION,val=22,str="Commit failed: Broker: Specified group generation id is not valid"}
